
export const types = {
    CREATE_USER: 'CREATE_USER',
    AUTHORIZE_USER: 'AUTHORIZED_USER',
    SET_CURRENT_PAGE: `SET_CURRENT_PAGE`,
    ADD_NEW_DONATOR: `ADD_NEW_DONATOR`,
    SET_DONATOR_LIST: `SET_DONATOR_LIST`,
    DELETE_ONE_DONATOR: `DELETE_ONE_DONATOR`,
    UPDATE_DONATOR: `UPDATE_DONATOR`,
    SET_FLASH_MESSAGE: `SET_FLASH_MESSAGE`,
    FETCH_USERS: `FETCH_USERS`,
    LOGOUT_USER: `LOGOUT_USER`,
    FETCH_EXPENSES: `FETCH_EXPENSES`,
}

